<?php
/**
 * @file
 * Code for the Restaurant Reservation feature.
 */

include_once 'restaurant_reservation.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */ 
function restaurant_reservation_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function restaurant_reservation_form_reservation_node_form_alter(&$form, &$form_state) {
  // When the form is not shown on admin pages, make some changes.
  if (!drupal_match_path(current_path(), "node/*/reservation")) {
    // Remove additional fields.
    $form['additional_settings']['#access'] = FALSE;
    $form['revision_information']['#access'] = FALSE;
    $form['path']['#access'] = FALSE;

    // Add an after_build callback.
    $form['#after_build'][] = 'restaurant_reservation_form_reservation_node_form_after_build';
  }
}

/**
 * Reservation form after_build callback.
 */
function restaurant_reservation_form_reservation_node_form_after_build($form) {
  // Hide the draft button.
  if (isset($form['actions']['draft'])) {
    $form['actions']['draft']['#access'] = FALSE;
  }

  // Change the value of the submit buttton.
  $form['actions']['submit']['#value'] = t('Submit Reservation');

  return $form;
}
